name: Deploy to Production (on release publish)

on:
  release:
    types: [published]

permissions:
  contents: read

concurrency:
  group: prod-deploy
  cancel-in-progress: false

jobs:
  backend:
    name: Backend → production
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Dummy prod deploy (backend)
        env:
          VERSION: ${{ github.event.release.tag_name }}
        run: echo "[prod] deployment (backend) — $VERSION"
