name: Deploy to Stage

on:
  push:
    branches:
      - main
      - hotfix/*

concurrency:
  group: stage-deploy
  cancel-in-progress: false

env:
  TZ: Europe/Berlin

jobs:
  backend:
    name: Backend → stage
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - uses: actions/checkout@v4
      - name: Release Variables
        id: vars
        run: |
          echo "version=$(TZ='Europe/Berlin' date +'%Y-%m-%d')-${GITHUB_SHA::7}" >> $GITHUB_OUTPUT
      - name: Dummy stage deploy (backend)
        run: echo "[stage] deployment (backend) — ${{ steps.vars.outputs.version }}"
