name: Deploy to Stage

on:
  workflow_run:
    workflows: ["Release Drafter"]
    branches: [main]
    types:
      - completed

concurrency:
  group: stage-deploy
  cancel-in-progress: false

env:
  TZ: Europe/Berlin

jobs:
  backend:
    name: Backend → stage
    runs-on: ubuntu-latest
    environment: staging
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v4
      - name: Get latest draft release version
        id: release_version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          version=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            "https://api.github.com/repos/${{ github.repository }}/releases/latest" | jq -r .tag_name)
          echo "VERSION=${version}" >> $GITHUB_ENV
      - name: Dummy stage deploy (backend)
        run: echo "[stage] deployment (backend) — $VERSION"
