name: Deploy to Production (on release publish)

on:
  release:
    types: [published]

permissions:
  contents: read

concurrency:
  group: prod-deploy
  cancel-in-progress: false

jobs:
  validate_tag:
    name: Validate tag format YYYY.MM.DD
    runs-on: ubuntu-latest
    steps:
      - name: Check tag against regex
        env:
          TAG: ${{ github.event.release.tag_name }}
        run: |
          echo "Release tag: $TAG"
          if [[ ! "$TAG" =~ ^[0-9]{4}\.(0[1-9]|1[0-2])\.(0[1-9]|[12][0-9]|3[01])(\.[0-9]+)?$ ]]; then
            echo "ERROR: Tag must be in format YYYY.MM.DD or YYYY.MM.DD.N (e.g., 2025.08.15 oder 2025.08.15.1)."
            exit 1
          fi

  backend:
    name: Backend → production
    runs-on: ubuntu-latest
    needs: validate_tag
    environment: production
    steps:
      - name: Dummy prod deploy (backend)
        env:
          VERSION: ${{ github.event.release.tag_name }}
        run: echo "[prod] deployment (backend) — $VERSION"
