name: Release Drafter

on:
  push:
    branches: [ development ]
  pull_request:
    types: [ opened, reopened, synchronize ]

permissions:
  contents: read

jobs:
  update_release_draft:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Set date environment variables
        run: |
          echo "YEAR=$(TZ='Europe/Berlin' date '+%Y')" >> $GITHUB_ENV
          echo "MONTH=$(TZ='Europe/Berlin' date '+%m')" >> $GITHUB_ENV
          echo "DAY=$(TZ='Europe/Berlin' date '+%d')" >> $GITHUB_ENV

      - uses: release-drafter/release-drafter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          YEAR: ${{ env.YEAR }}
          MONTH: ${{ env.MONTH }}
          DAY: ${{ env.DAY }}
