name: Release Drafter

on:
  push:
    branches: [ development ]
  pull_request:
    types: [ opened, reopened, synchronize ]

permissions:
  contents: read

jobs:
  update_release_draft:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Get current date in Europe/Berlin timezone
        id: date
        run: |
          echo "date=$(TZ='Europe/Berlin' date +'%Y.%m.%d')" >> $GITHUB_OUTPUT

      - name: Debug
        run: |
          echo "Date: ${{ steps.date.outputs.date }}"
          echo "Run ID: $GITHUB_RUN_ID"

      - uses: release-drafter/release-drafter@v6
        with:
          name: '${{ steps.date.outputs.date }}+${{ github.run_id }}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
