name: Release Drafter

on:
  push:
    branches: [ main ]
  pull_request:
    types: [ opened, reopened, synchronize ]

permissions:
  contents: read

jobs:
  update_release_draft:
    concurrency:
      group: release-creation
      cancel-in-progress: false
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
      - name: Release Variables
        id: vars
        run: |
          echo "version=$(TZ='Europe/Berlin' date +'%Y-%m-%d')-${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - uses: release-drafter/release-drafter@v6
        with:
          version: '${{ steps.vars.outputs.version }}'
          name: '${{ steps.vars.outputs.version }}'
          tag: '${{ steps.vars.outputs.version }}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
